"""Toolchain discovery and contract generation for ``dunnit init``.

Detection is deliberately evidence based.  A generic project manifest is not
enough to assume a test runner; a repository must advertise the runner through
configuration, dependencies, scripts, or conventional test files.
"""

from __future__ import annotations

import json
import re
import shlex
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path, PurePosixPath, PureWindowsPath
from typing import Any, cast

import yaml

PRESETS = ("auto", "python", "node", "go", "rust", "mixed")

_DEDICATED_CONFIGS = (
    "pytest.ini",
    "tox.ini",
    "noxfile.py",
    "jest.config.js",
    "jest.config.ts",
    "vitest.config.js",
    "vitest.config.ts",
    "playwright.config.js",
    "playwright.config.ts",
    "cypress.config.js",
    "cypress.config.ts",
)


@dataclass(frozen=True)
class DetectedCheck:
    """A proof command supported by a concrete repository signal."""

    name: str
    argv: list[str]
    directory: str | None = None
    source: str = ""


@dataclass
class Detection:
    checks: list[DetectedCheck] = field(default_factory=list)
    protected: list[str] = field(default_factory=lambda: ["dod.yaml", ".github/**"])
    test_globs: list[str] = field(default_factory=list)
    sources: list[str] = field(default_factory=list)
    issues: list[str] = field(default_factory=list)


def detect(cwd: Path, preset: str = "auto") -> Detection:
    """Discover high-confidence checks and materialize their evidence sources."""

    if preset not in PRESETS:
        raise ValueError(f"unknown preset: {preset}")
    selected = {"python", "node", "go", "rust"} if preset in {"auto", "mixed"} else {preset}
    result = Detection()

    if "python" in selected:
        _detect_python(cwd, result)
    if "node" in selected:
        _detect_node(cwd, result)
    if "go" in selected:
        _detect_go(cwd, result)
    if "rust" in selected:
        _detect_rust(cwd, result)

    for name in _DEDICATED_CONFIGS:
        if (cwd / name).is_file() and name not in result.protected:
            result.protected.append(name)
    result.sources = sorted(set(result.sources))
    result.protected = list(dict.fromkeys(result.protected))
    result.test_globs = list(dict.fromkeys(result.test_globs))
    duplicate_names = sorted(
        name for name, count in Counter(item.name for item in result.checks).items() if count > 1
    )
    if duplicate_names:
        result.issues.append(
            "detected workspace paths produce duplicate check names: "
            + ", ".join(duplicate_names)
        )
    return result


def render_contract(detection: Detection, *, base: str | None = None) -> str:
    """Render a self-contained v2 contract; presets are never runtime inputs."""

    if detection.issues:
        raise ValueError("; ".join(detection.issues))
    if not detection.checks:
        raise ValueError("no proof commands were detected; no contract was written")
    data: dict[str, object] = {"version": 2}
    if base:
        data["base"] = base
    checks: list[dict[str, object]] = []
    for check in detection.checks:
        item: dict[str, object] = {
            "name": check.name,
            "argv": check.argv,
            "timeout": 600,
            "dir": check.directory or ".",
            "env": {"CI": "1"},
            "writes": [],
        }
        checks.append(item)
    data.update(
        {
            "checks": checks,
            "protected": detection.protected,
            "test_globs": detection.test_globs,
            "tamper": True,
            "stubs": True,
            "strict": False,
        }
    )
    body = yaml.safe_dump(data, sort_keys=False, width=100)
    header = (
        "# dunnit v2 definition of done\n"
        "# Generated from repository evidence; review before committing.\n"
    )
    rendered = header + body
    # Generation must never leave a user with YAML which Dunnit's own runtime
    # rejects (for example colliding workspace slugs).
    from dunnit.contract import parse_contract

    parse_contract(rendered, source="generated by dunnit init")
    return rendered


def _detect_python(cwd: Path, result: Detection) -> None:
    pyproject = _read(cwd / "pyproject.toml")
    setup_cfg = _read(cwd / "setup.cfg")
    requirement_paths = [
        path for path in sorted(cwd.glob("requirements*.txt")) if path.is_file()
    ]
    declaring_requirements = [
        path for path in requirement_paths if _requirements_declare_pytest(_read(path))
    ]
    pytest_ini = (cwd / "pytest.ini").is_file()
    conftest = (cwd / "conftest.py").is_file()
    pyproject_pytest = bool(
        re.search(r"(?im)^\s*\[tool\.pytest(?:\.[^\]]+)?\]\s*(?:#.*)?$", pyproject)
    )
    setup_pytest = bool(re.search(r"(?im)^\s*\[(?:tool:)?pytest\]\s*(?:[#;].*)?$", setup_cfg))
    pyproject_declares_pytest = _pyproject_declares_pytest(pyproject)
    declared_pytest = bool(declaring_requirements) or pyproject_declares_pytest
    configured = bool(
        pytest_ini
        or conftest
        or pyproject_pytest
        or setup_pytest
        or declared_pytest
    )
    # Filenames alone do not identify the runner: unittest, pytest, nose, and
    # project-specific harnesses all commonly use ``test_*.py``. Materialize
    # pytest only from a configuration/plugin/dependency signal.
    if configured:
        result.checks.append(
            DetectedCheck("tests", ["python", "-m", "pytest", "-q"], source="pytest evidence")
        )
        result.sources.append("pytest")
        result.test_globs.extend(
            ["tests/**", "test/**", "**/test_*.py", "**/*_test.py"]
        )
        if pytest_ini:
            result.protected.append("pytest.ini")
        if conftest:
            result.protected.append("conftest.py")
        if pyproject_pytest or pyproject_declares_pytest:
            result.protected.append("pyproject.toml")
        if setup_pytest:
            result.protected.append("setup.cfg")
        result.protected.extend(path.relative_to(cwd).as_posix() for path in declaring_requirements)
    pyproject_ruff = bool(
        re.search(r"(?im)^\s*\[tool\.ruff(?:\.[^\]]+)?\]\s*(?:#.*)?$", pyproject)
    )
    setup_ruff = bool(re.search(r"(?im)^\s*\[ruff(?:\.[^\]]+)?\]\s*(?:[#;].*)?$", setup_cfg))
    if pyproject_ruff or setup_ruff:
        result.checks.append(
            DetectedCheck("lint", ["python", "-m", "ruff", "check", "."], source="ruff config")
        )
        result.sources.append("ruff")
        result.protected.append("pyproject.toml" if pyproject_ruff else "setup.cfg")


def _detect_node(cwd: Path, result: Detection) -> None:
    root_path = cwd / "package.json"
    root_manifest = _load_package(root_path)
    roots: list[tuple[Path, dict[str, Any]]] = []
    if root_path.is_file() and root_manifest is None:
        result.issues.append("package.json is not a valid JSON object")
    if root_manifest is not None:
        roots.append((cwd, root_manifest))
        workspaces, workspace_issues = _node_workspaces(cwd, root_manifest)
        roots.extend(workspaces)
        result.issues.extend(workspace_issues)
    for directory, manifest in roots:
        scripts = manifest.get("scripts", {})
        if not isinstance(scripts, dict):
            continue
        rel = directory.relative_to(cwd).as_posix()
        workdir = None if rel == "." else rel
        managers, manager_issue = _node_managers(directory, cwd, manifest, root_manifest)
        if manager_issue:
            result.issues.append(f"{rel}: {manager_issue}")
            continue
        if len(managers) > 1:
            result.issues.append(
                f"multiple Node lockfiles or packageManager signals select different "
                f"package managers for {rel}: "
                + ", ".join(managers)
            )
            continue
        manager = managers[0] if managers else "npm"
        suffix = "" if workdir is None else "-" + _slug(rel)
        selected_script = False
        if _usable_node_script(scripts.get("test"), kind="test"):
            selected_script = True
            result.checks.append(
                DetectedCheck(
                    "node-tests" + suffix,
                    _node_script_argv(manager, "test"),
                    workdir,
                    f"{rel}/package.json scripts.test",
                )
            )
            result.sources.append(f"{rel}/package.json#scripts.test")
            prefix = "" if workdir is None else workdir + "/"
            result.test_globs.extend(
                [
                    prefix + "__tests__/**",
                    prefix + "**/*.test.*",
                    prefix + "**/*.spec.*",
                ]
            )
        if _usable_node_script(scripts.get("lint"), kind="lint"):
            selected_script = True
            result.checks.append(
                DetectedCheck(
                    "node-lint" + suffix,
                    _node_script_argv(manager, "lint"),
                    workdir,
                    f"{rel}/package.json scripts.lint",
                )
            )
            result.sources.append(f"{rel}/package.json#scripts.lint")
        if selected_script:
            package_path = directory.relative_to(cwd) / "package.json"
            result.protected.append(package_path.as_posix())
            result.protected.append("package.json")
            if (cwd / "pnpm-workspace.yaml").is_file():
                result.protected.append("pnpm-workspace.yaml")
            for base in dict.fromkeys((directory, cwd)):
                for lockfile in (
                    "package-lock.json",
                    "pnpm-lock.yaml",
                    "yarn.lock",
                    "bun.lock",
                    "bun.lockb",
                ):
                    path = base / lockfile
                    if path.is_file():
                        result.protected.append(path.relative_to(cwd).as_posix())


def _detect_go(cwd: Path, result: Detection) -> None:
    workspace = cwd / "go.work"
    root_module = cwd / "go.mod"
    if workspace.is_file():
        modules, issues = _go_workspace_modules(cwd)
        result.issues.extend(issues)
        if not modules and not issues:
            result.issues.append("go.work declares no usable module paths")
        for module in modules:
            relative = module.relative_to(cwd).as_posix()
            directory = None if relative == "." else relative
            suffix = "" if directory is None and len(modules) == 1 else "-" + _slug(relative)
            source = f"go.work use {relative}"
            result.checks.extend(
                [
                    DetectedCheck(
                        "go-tests" + suffix,
                        ["go", "test", "./..."],
                        directory,
                        source,
                    ),
                    DetectedCheck(
                        "go-vet" + suffix,
                        ["go", "vet", "./..."],
                        directory,
                        source,
                    ),
                ]
            )
            prefix = "" if directory is None else directory + "/"
            result.test_globs.append(prefix + "**/*_test.go")
        if modules:
            result.sources.append("go.work")
            result.protected.append("go.work")
            result.protected.extend(
                (module.relative_to(cwd) / "go.mod").as_posix() for module in modules
            )
        return

    if root_module.is_file():
        result.checks.extend(
            [
                DetectedCheck("go-tests", ["go", "test", "./..."], source="go.mod"),
                DetectedCheck("go-vet", ["go", "vet", "./..."], source="go.mod"),
            ]
        )
        result.sources.append("go.mod")
        result.test_globs.append("**/*_test.go")
        result.protected.append("go.mod")


def _detect_rust(cwd: Path, result: Detection) -> None:
    if (cwd / "Cargo.toml").is_file():
        argv = ["cargo", "test", "--quiet"]
        if "[workspace]" in _read(cwd / "Cargo.toml"):
            argv.insert(2, "--workspace")
        result.checks.append(DetectedCheck("rust-tests", argv, source="Cargo.toml"))
        result.sources.append("Cargo.toml")
        result.test_globs.extend(["tests/**", "**/tests/**"])
        result.protected.append("Cargo.toml")
        if (cwd / ".cargo" / "config.toml").is_file():
            result.protected.append(".cargo/config.toml")


def _load_package(path: Path) -> dict[str, Any] | None:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, ValueError):
        return None
    return cast(dict[str, Any], value) if isinstance(value, dict) else None


def _node_workspaces(
    cwd: Path, manifest: dict[str, Any]
) -> tuple[list[tuple[Path, dict[str, Any]]], list[str]]:
    issues: list[str] = []
    raw = manifest.get("workspaces", [])
    if isinstance(raw, dict):
        raw = raw.get("packages", [])
    if "workspaces" in manifest and not isinstance(raw, list):
        issues.append("package.json workspaces must be a list of repository-relative globs")
        raw = []
    pnpm_patterns, pnpm_issues = _pnpm_workspace_patterns(cwd)
    issues.extend(pnpm_issues)
    raw = [*raw, *pnpm_patterns]
    found: list[tuple[Path, dict[str, Any]]] = []
    seen: set[Path] = set()
    excluded: set[Path] = set()
    valid: list[tuple[str, bool]] = []
    for pattern in raw:
        if not isinstance(pattern, str):
            issues.append("workspace patterns must be strings")
            continue
        exclude = pattern.startswith("!")
        candidate_pattern = pattern[1:] if exclude else pattern
        problem = _workspace_pattern_problem(candidate_pattern)
        if problem:
            issues.append(f"invalid workspace pattern {pattern!r}: {problem}")
            continue
        valid.append((candidate_pattern, exclude))

    for pattern, exclude in valid:
        if not exclude:
            continue
        try:
            matches = sorted(cwd.glob(pattern))
        except (OSError, ValueError, NotImplementedError) as exc:
            issues.append(f"invalid workspace pattern {pattern!r}: {exc}")
            continue
        for directory in matches:
            try:
                excluded.add(directory.resolve())
            except OSError:
                continue

    for pattern, exclude in valid:
        if exclude:
            continue
        try:
            matches = sorted(cwd.glob(pattern))
        except (OSError, ValueError, NotImplementedError) as exc:
            issues.append(f"invalid workspace pattern {pattern!r}: {exc}")
            continue
        if not matches:
            issues.append(f"workspace pattern {pattern!r} matched no paths")
            continue
        for directory in matches:
            try:
                resolved = directory.resolve()
                resolved.relative_to(cwd.resolve())
            except (OSError, ValueError):
                continue
            if resolved in seen or resolved in excluded:
                continue
            manifest_path = directory / "package.json"
            package = _load_package(manifest_path)
            relative = directory.relative_to(cwd).as_posix()
            if not manifest_path.is_file():
                issues.append(f"workspace {relative!r} has no package.json")
                continue
            if package is None:
                issues.append(f"workspace {relative!r} package.json is not a JSON object")
                continue
            seen.add(resolved)
            found.append((directory, package))
    return found, issues


def _pnpm_workspace_patterns(cwd: Path) -> tuple[list[str], list[str]]:
    path = cwd / "pnpm-workspace.yaml"
    if not path.is_file():
        return [], []
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except (OSError, UnicodeError, yaml.YAMLError, RecursionError) as exc:
        return [], [f"could not parse pnpm-workspace.yaml: {exc}"]
    if not isinstance(data, dict) or not isinstance(data.get("packages"), list):
        return [], ["pnpm-workspace.yaml must contain a packages list"]
    invalid = [item for item in data["packages"] if not isinstance(item, str)]
    issues = ["pnpm workspace patterns must be strings"] if invalid else []
    return [item for item in data["packages"] if isinstance(item, str)], issues


def _node_managers(
    directory: Path,
    root: Path,
    manifest: dict[str, Any],
    root_manifest: dict[str, Any] | None,
) -> tuple[list[str], str | None]:
    managers: list[str] = []
    for candidate in (manifest, root_manifest):
        if candidate is None:
            continue
        declared = candidate.get("packageManager")
        if declared is None:
            continue
        if not isinstance(declared, str) or not declared.strip():
            return managers, "packageManager must be a non-empty string"
        manager = declared.split("@", 1)[0].lower()
        if manager not in {"npm", "pnpm", "yarn", "bun"}:
            return managers, f"unsupported declared packageManager {declared!r}"
        if manager not in managers:
            managers.append(manager)
    for base in (directory, root):
        candidates = [
            ("pnpm", (base / "pnpm-lock.yaml").is_file()),
            ("yarn", (base / "yarn.lock").is_file()),
            ("bun", (base / "bun.lock").is_file() or (base / "bun.lockb").is_file()),
            ("npm", (base / "package-lock.json").is_file()),
        ]
        for manager, present in candidates:
            if present and manager not in managers:
                managers.append(manager)
    return managers, None


def _go_workspace_modules(root: Path) -> tuple[list[Path], list[str]]:
    """Read literal ``go.work use`` paths without invoking candidate tooling."""

    text = _read(root / "go.work")
    paths: list[Path] = []
    issues: list[str] = []
    in_use_block = False
    for number, raw_line in enumerate(text.splitlines(), start=1):
        line = raw_line.split("//", 1)[0].strip()
        if not line:
            continue
        if in_use_block:
            if line == ")":
                in_use_block = False
                continue
            value = line
        elif re.fullmatch(r"use\s*\(", line):
            in_use_block = True
            continue
        elif line.startswith("use "):
            value = line[4:].strip()
        else:
            continue
        if len(value) >= 2 and value.startswith("`") and value.endswith("`"):
            tokens = [value[1:-1]]
        else:
            try:
                tokens = shlex.split(value, comments=True, posix=True)
            except ValueError as exc:
                issues.append(f"go.work:{number}: invalid use path: {exc}")
                continue
        if len(tokens) != 1:
            issues.append(f"go.work:{number}: each use directive must name one module path")
            continue
        token = tokens[0].strip("`")
        candidate = (root / token).resolve()
        try:
            candidate.relative_to(root.resolve())
        except (OSError, ValueError):
            issues.append(f"go.work:{number}: module path escapes the repository: {token}")
            continue
        if not (candidate / "go.mod").is_file():
            issues.append(f"go.work:{number}: module has no go.mod: {token}")
            continue
        paths.append(candidate)
    if in_use_block:
        issues.append("go.work: unterminated use block")
    return list(dict.fromkeys(paths)), issues


def _usable_node_script(value: object, *, kind: str) -> bool:
    if not isinstance(value, str) or not value.strip():
        return False
    lowered = value.lower()
    if kind == "test" and "no test specified" in lowered and "exit 1" in lowered:
        return False
    stripped = lowered.strip().rstrip(";").strip()
    if stripped in {":", "true", "exit 0", "exit /b 0"}:
        return False
    return not (
        re.match(r"^(?:echo|printf)\b", stripped)
        and not re.search(r"(?:&&|\|\||[;|])", stripped)
    )


def _node_script_argv(manager: str, script: str) -> list[str]:
    if manager == "npm":
        return ["npm", "run", script, "--silent"]
    return [manager, "run", script]


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        return ""


def _workspace_pattern_problem(pattern: str) -> str | None:
    if not pattern:
        return "pattern must not be empty"
    normalized = pattern.replace("\\", "/")
    posix = PurePosixPath(normalized)
    windows = PureWindowsPath(pattern)
    if posix.is_absolute() or windows.is_absolute() or windows.drive:
        return "pattern must be relative to the repository root"
    if ".." in posix.parts:
        return "pattern must stay within the repository root"
    return None


def _requirements_declare_pytest(text: str) -> bool:
    return bool(
        re.search(
            r"(?im)^\s*pytest(?:[-_.][a-z0-9]+)*(?:\[[^\]]+\])?\s*"
            r"(?:[<>=!~;@].*|(?:#.*)?$)",
            text,
        )
    )


def _pyproject_declares_pytest(text: str) -> bool:
    package = r'''pytest(?:[-_.][a-z0-9]+)*(?:\[[^\]'\"]+\])?'''
    quoted = re.compile(rf"[\"']\s*{package}\s*(?=[<>=!~;@\"'])", re.IGNORECASE)
    direct = re.compile(rf"^\s*[\"']?{package}[\"']?\s*=", re.IGNORECASE)
    section = ""
    dependency_array = False
    for raw_line in text.splitlines():
        header = re.fullmatch(r"\s*\[([^\]]+)\]\s*(?:#.*)?", raw_line)
        if header:
            section = header.group(1).strip().casefold()
            dependency_array = False
            continue

        line = raw_line.strip()
        poetry_dependencies = section == "tool.poetry.dependencies" or bool(
            re.fullmatch(r"tool\.poetry\.group\.[^.]+\.dependencies", section)
        )
        if poetry_dependencies and direct.match(line):
            return True

        assignment = re.match(r"^\s*([a-zA-Z0-9_.-]+)\s*=\s*(.*)$", raw_line)
        value = assignment.group(2) if assignment else ""
        key = assignment.group(1).casefold() if assignment else ""
        dependency_group = section.startswith(
            ("project.optional-dependencies", "tool.pdm.dev-dependencies")
        )
        hatch_dependencies = section.startswith("tool.hatch.envs.") and key == "dependencies"
        array_field = assignment is not None and (
            (section == "project" and key == "dependencies")
            or dependency_group
            or section == "dependency-groups"
            or (section == "tool.uv" and key == "dev-dependencies")
            or hatch_dependencies
        )
        if array_field:
            if quoted.search(value):
                return True
            dependency_array = value.count("[") > value.count("]")
            continue
        if dependency_array:
            if quoted.search(raw_line):
                return True
            if raw_line.count("]") > raw_line.count("["):
                dependency_array = False
    return False


def _slug(path: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", path.lower()).strip("-") or "root"
